import pandas as pd
import glob
import matplotlib.pyplot as plt
import os
import pypandoc
import shutil



def get_geneset_to_acc(result_folder:str) -> dict:
    """Get Gene Set and their associated ACC from results files generated by classifiers
    
    Args:
        - result_folder (str) : path to the folder containing the results files

    Returns:
        - (dict) : name of gene set associated to an accuracy
    
    """

    # init dict
    geneset_to_acc = {}
    
    # loop over result files
    result_files = glob.glob(f"{result_folder}/*.csv")
    for rf in result_files:

        # extract gene name
        geneset = rf.split("/")[-1].replace("_log_clf.csv", "")

        # get acc from results
        df = pd.read_csv(rf)
        df = df[df['METRIC'] == 'ACC']
        acc = list(df['VALUE'])[0]

        # update dict
        geneset_to_acc[geneset] = acc

    # return dict
    return geneset_to_acc
        

def get_geneset_to_auc(result_folder:str) -> dict:
    """Get Gene Set and their associated AUC from results files generated by classifiers
    
    Args:
        - result_folder (str) : path to the folder containing the results files

    Returns:
        - (dict) : name of gene set associated to an auc
    
    """

    # init dict
    geneset_to_acc = {}
    
    # loop over result files
    result_files = glob.glob(f"{result_folder}/*.csv")
    for rf in result_files:

        # extract gene name
        geneset = rf.split("/")[-1].replace("_log_clf.csv", "")

        # get acc from results
        df = pd.read_csv(rf)
        df = df[df['METRIC'] == 'AUC']
        acc = list(df['VALUE'])[0]

        # update dict
        geneset_to_acc[geneset] = acc

    # return dict
    return geneset_to_acc
    

def plot_acc(result_folder:str, figure_file:str) -> None:
    """Generate figure of sorted acc from results
    
    Args:
        - result_folder (str) : path to the folder containing the results files
        - figure_file (str) : path to save figure
    
    """

    # get acc
    geneset_to_acc =get_geneset_to_acc(result_folder)
    
    # sort gene sets by acc
    sorted_items = sorted(geneset_to_acc.items(), key=lambda x: x[1])

    # unpack & clean acc
    names, accs = zip(*sorted_items)
    accs = [round(float(f), 5) for f in accs]

    # craft figure
    plt.figure(figsize=(8, 5))
    plt.barh(names, accs)
    plt.xlabel("ACC")
    plt.ylabel("Gene Set")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(figure_file)
    plt.close()


def plot_auc(result_folder:str, figure_file:str) -> None:
    """Generate figure of sorted auc from results
    
    Args:
        - result_folder (str) : path to the folder containing the results files
        - figure_file (str) : path to save figure
    
    """

    # get acc
    geneset_to_acc =get_geneset_to_auc(result_folder)
    
    # sort gene sets by acc
    sorted_items = sorted(geneset_to_acc.items(), key=lambda x: x[1])

    # unpack & clean acc
    names, accs = zip(*sorted_items)
    accs = [round(float(f), 5) for f in accs]

    # craft figure
    plt.figure(figsize=(8, 5))
    plt.barh(names, accs)
    plt.xlabel("AUC")
    plt.ylabel("Gene Set")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(figure_file)
    plt.close()


def extract_config_from_results(result_folder:str) -> dict:
    """Extract configuration from files in result folders, make sure every file has the same configuration
    
    Args:
        - result_folder (str) : path to the folder containing the results files

    Returns:
        - (dict) : configuration of the run
        
    """

    # init config
    config = {}
    j_list = []
    q_list = []
    audio_duration_list = []
    clf_list = []
    
    # loop over result files
    result_files = glob.glob(f"{result_folder}/*.csv")
    for rf in result_files:

        # get infos from results
        df = pd.read_csv(rf)
        j_list.append(list(df[df['METRIC'] == "J"]['VALUE'])[0])
        q_list.append(list(df[df['METRIC'] == "Q"]['VALUE'])[0])
        audio_duration_list.append(list(df[df['METRIC'] == "Audio-Duration"]['VALUE'])[0])
        clf_list.append(list(df[df['METRIC'] == "CLF"]['VALUE'])[0])

    # check that all extracted config are the same
    if len(list(set(j_list))) == 1:
        config['J'] = j_list[0]
    else:
        config['J'] = 'WARNING : Multiple Values Found'
    if len(list(set(q_list))) == 1:
        config['Q'] = q_list[0]
    else:
        config['Q'] = 'WARNING : Multiple Values Found'
    if len(list(set(audio_duration_list))) == 1:
        config['Audio-Duration'] = audio_duration_list[0]
    else:
        config['Audio-Duration'] = 'WARNING : Multiple Values Found'
    if len(list(set(clf_list))) == 1:
        config['CLF'] = clf_list[0]
    else:
        config['CLF'] = 'WARNING : Multiple Values Found'

    # return config
    return config        


def extract_data_infos(signal_folder:str) -> dict:
    """Extract infos about data from signal folder

    Args:
        - signal_folder (str) : path to the folder containing signals (.wav) files

    Returns:
        - (dict) : extracted informations
    
    """

    # init
    infos = {
        "n_genes_sets":None,
        "n_class":None
    }

    # count gene sets
    fld_list = []
    for fld in glob.glob(f"{signal_folder}/*"):
        if os.path.isdir(fld):
            fld_list.append(fld)
    infos['n_genes_sets'] = len(fld_list)

    # get nb class
    class_folder_list = []
    if len(fld_list) > 0:
        for cfld in glob.glob(f"{fld_list[0]}/*"):
            if os.path.isdir(fld):
                class_folder_list.append(cfld)
    infos['n_class'] = len(class_folder_list)

    # get class to n_samples
    for class_folder in class_folder_list:
        class_name = class_folder.split("/")[-1]
        infos[f"n_{class_name}"] = 0
        for sig_file in glob.glob(f"{class_folder}/*.wav"):
            infos[f"n_{class_name}"] += 1

    return infos               


def craft_run_report(run_folder:str):
    """ """


    # prepare folders for report generation
    if os.path.exists(f"{run_folder}/report") and os.path.isdir(f"{run_folder}/report"):
        shutil.rmtree(f"{run_folder}/report")
    os.mkdir(f"{run_folder}/report")

    # extract informations
    gene_set_to_acc = get_geneset_to_acc(f"{run_folder}/results") 
    gene_set_to_auc = get_geneset_to_acc(f"{run_folder}/results") 
    infos = extract_config_from_results(f"{run_folder}/signals")    

    # generate markdown report
    md_report = open(f"{run_folder}/report/report.md", "w")
    md_report.write("# Run Report\n")
    md_report.write("## Data\n")
    md_report.write("## Clf Perfs\n")
    md_report.close()

    # convert md to pdf
    pypandoc.convert_file(
        f"{run_folder}/report/report.md",
        to='pdf',
        outputfile=f"{run_folder}/report/report.pdf",
        extra_args=[
        '--from=markdown',       # Spécifie que l'entrée est du Markdown
        '--pdf-engine=xelatex'   # Utilise xelatex comme moteur LaTeX (plus flexible que pdflatex)
    ]
    )
    



if __name__ == "__main__":

    # plot_auc("/tmp/zog/results", "/tmp/test.png")
    # machin = extract_config_from_results("/tmp/zog/results")
    # extract_data_infos("/tmp/zog/signals")
    craft_run_report("/tmp/zog")

    
